// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8uwwVZn_EdIlQ1QmfmokvIKRlfw_riuA',
    appId: '1:267999091045:web:62fcd8d986e633903f698c',
    messagingSenderId: '267999091045',
    projectId: 'mobile-finals-2024',
    authDomain: 'mobile-finals-2024.firebaseapp.com',
    storageBucket: 'mobile-finals-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5doGPdIMNZa3j5_ZbQZDzLTe2zd2iLk8',
    appId: '1:267999091045:android:5b23fbbde5e7d4133f698c',
    messagingSenderId: '267999091045',
    projectId: 'mobile-finals-2024',
    storageBucket: 'mobile-finals-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4qiBta5Sh9SrmkHymUgrPLxQrAZbu6ik',
    appId: '1:267999091045:ios:ba0bb02320f6dc4a3f698c',
    messagingSenderId: '267999091045',
    projectId: 'mobile-finals-2024',
    storageBucket: 'mobile-finals-2024.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4qiBta5Sh9SrmkHymUgrPLxQrAZbu6ik',
    appId: '1:267999091045:ios:ba0bb02320f6dc4a3f698c',
    messagingSenderId: '267999091045',
    projectId: 'mobile-finals-2024',
    storageBucket: 'mobile-finals-2024.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8uwwVZn_EdIlQ1QmfmokvIKRlfw_riuA',
    appId: '1:267999091045:web:59b6c500290cad693f698c',
    messagingSenderId: '267999091045',
    projectId: 'mobile-finals-2024',
    authDomain: 'mobile-finals-2024.firebaseapp.com',
    storageBucket: 'mobile-finals-2024.appspot.com',
  );
}
